<?xml version="1.0"?>
<!--
    Ningauble of The Seven Eyes
    Iain Brookshaw
    Copyright (c), 2020. All Rights Reserved
    MIT License
-->
<robot name="ningauble" xmlns:xacro="http://ros.org/wiki/xacro">
  
    <!-- Chassis Constants -->
    <xacro:property name="chassis_height"   value="0.05"/>
    <xacro:property name="chassis_diameter" value="0.2" />
    <xacro:property name="chassis_center"   value="0 0 ${chassis_height / 2.0}" />
    <xacro:property name="chassis_mass"     value="1.0" />

    <link name="chassis">
        <visual>
            <geometry>
                <cylinder radius="${chassis_diameter/2.0}" length="${chassis_height}"/>
                <origin xyz="${chassis_center}" />
            </geometry>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${chassis_diameter/2.0}" length="${chassis_height}"/>
                <origin xyz="${chassis_center}" />
            </geometry>
        </collision>

        <xacro:default_inertial mass="${chassis_mass}"/>

        <!-- TODO: GAZEBO PLUGIN FOR CHASSIS SENSORS GOES HERE -->
    </link>
</robot>
