<?xml version="1.0"?>
<!--
    Ningauble of The Seven Eyes
    Iain Brookshaw
    Copyright (c), 2020. All Rights Reserved
    MIT License

    This should work with both Gazebo and RViz
    see https://github.com/ros/urdf_sim_tutorial/blob/master/urdf/13-diffdrive.urdf.xacro
    for a base example
-->
<robot name="ningauble" xmlns:xacro="http://ros.org/wiki/xacro">

    <!--
        Define Robot Constants

        These are for geometry only. Physics constants for the simulator 
        are in ningauble.gazebo
    -->
    <xacro:include filename="$(find ning_urdf)/urdf/math.xacro" />

    <!-- Chassis Constants -->
    <xacro:property name="chassis_height"   value="0.05"     />
    <xacro:property name="chassis_diameter" value="0.2"      />
    <xacro:property name="chassis_center"   value="0 0 ${chassis_height / 2.0}" />
    <xacro:property name="chassis_mass"     value="1.0"      />

    <!-- Drive Wheels Constants -->
    <xacro:property name="wheel_base"      value="${chassis_diameter}"/>
    <xacro:property name="wheel_diameter"  value="0.05"  />
    <xacro:property name="wheel_thickness" value="0.005" />
    <xacro:property name="wheel_mass"      value="0.001" />
    <xacro:property name="wheel_axel_x"    value="0.01" />

    <!-- Head Constants -->
    <xacro:property name="head_center" value="0 0 ${chassis_height / 2.0 + 1}" />
    <xacro:property name="head_mass"   value="2.0" />


    <!-- load the physics constants for the Gazebo Simulator -->
    <!-- <xacro:include filename="$(find ning_urdf)/urdf/ningauble.gazebo" /> -->

    <!-- Load all the Links -->
    <xacro:include filename="$(find ning_urdf)/urdf/head.xacro" origin="${head_center}" mass="${head_mass}"/>
    <!-- <xacro:include filename="$(find ning_urdf)/urdf/chassis/chassis.xacro"/> -->
    <!-- <xacro:include filename="$(find ning_urdf)/urdf/legs/legs.xacro"/> -->
    <!-- <xacro:wheel prefix="front_right" reflect_x="1"   reflect_y="1" /> -->
    <!-- <xacro:wheel prefix="back_left"   reflect_x="-1"  reflect_y="-1" /> -->
    <!-- <xacro:wheel prefix="front_right" reflect_x="1"   reflect_y="-1" /> -->
    <!-- <xacro:wheel prefix="right" reflect="1"  /> --> 

    <!-- Set up all the joints -->



  

</robot>