
    <!--
        Drive Wheel Links and Joints

        These are defined as an XACRO macro to make them duplicates
        mirror using the 'reflect' param: 1 is one side -1 the other
    -->
    <!-- <xacro:macro name="wheel" params="prefix reflect">

        <link name="${prefix}_wheel">
            <visual>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
                <geometry>
                    <mesh filename="package://ning_urdf/urdf/meshes/dae/ningauble_wheel.dae"/>
                </geometry>
            </visual>

            <collision>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
                <geometry>
                    <cylinder radius="${wheel_diameter/2}" length="${wheel_thickness}"/>
                </geometry>
            </collision>
    
            <xacro:default_inertial mass="${wheel_mass}"/>
        </link>

        <joint name="${prefix}_wheel_joint" type="continuous" >
            <axis xyz="0 1 0" rpy="0 0 0" />
            <parent link="chassis" />
            <child link="${prefix}_wheel"/>
            <origin xyz="${wheel_axel_x} ${0.005*reflect + wheel_base*reflect/2.0} -${wheel_diameter/2.0}" rpy="0 0 0"/>
        </joint>

    </xacro:macro> -->
